
const API='http://localhost:8000',OFF=5000;
const state={
  caseData:null,selected:[],focused:null,transform:{
    x:360,y:80,scale:1
  }
,draggingCanvas:false,pending:new Map()
}
;
const wrap=document.getElementById('wrap'),content=document.getElementById('content'),links=document.getElementById('links'),nodes=document.getElementById('nodes'),fileList=document.getElementById('fileList'),selectionList=document.getElementById('selectionList'),empty=document.getElementById('empty'),caseTitle=document.getElementById('caseTitle'),statusEl=document.getElementById('status'),promptEl=document.getElementById('prompt'),uploadZone=document.getElementById('uploadZone');
            const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
            const setStatus=(m)=>statusEl.textContent=m;
            const json=async r=>{if(!r.ok){const t=await r.text();throw new Error(t||('HTTP '+r.status))}return r.json()};
            const allCards=()=>state.caseData?[...state.caseData.meta_cards,...state.caseData.inference_cards,...state.caseData.law_cards]:[];
            const cardMap=()=>new Map(allCards().map(c=>[c.id,c]));
            const modeOf=t=>{t=t.trim().toLowerCase();if(!t)return'hypothesis';if(['冲突','矛盾','对比','conflict'].some(k=>t.includes(k)))return'conflict_check';if(['缺失','待验证','补证','missing'].some(k=>t.includes(k)))return'missing_evidence';return'hypothesis'};
            const genScope=()=>state.selected.length?state.selected.slice():(state.caseData?.meta_cards||[]).slice(0,4).map(c=>c.id);
            const icon=k=>({person:'人',organization:'组',legal:'法',conflict:'冲',missing:'缺'})[k]||'推';
            const decisionLabel=v=>v==='accepted'?'确认冲突':v==='rejected'?'已驳回':v==='pending'?'暂存':v==='undecided'?'待确认':'未处理';
            const levelLabel=v=>v===3?'详情':v===2?'概要':'胶囊';
            const typeMeta=c=>c.card_type==='meta'?`${c.info_type} / ${c.info_subtype}`:c.card_type==='law'?`法条 / ${`${c.source_type} / ${c.norm_level}`}`:c.inference_type==='conflict'?`冲突 / ${decisionLabel(c.decision)}`:c.inference_type==='missing_evidence'?'待验证点':'推理卡';
            const kindOf=c=>c.card_type==='meta'?(c.info_subtype||c.info_type):c.card_type==='law'?'legal':c.inference_type==='conflict'?'conflict':c.inference_type==='missing_evidence'?'missing':'hypothesis';
            function fallback(c,i){const mi=state.caseData.meta_cards.findIndex(x=>x.id===c.id),ii=state.caseData.inference_cards.findIndex(x=>x.id===c.id),li=state.caseData.law_cards.findIndex(x=>x.id===c.id);if(c.card_type==='meta')return{x:80+(mi%2)*360,y:80+Math.floor(mi/2)*240};if(c.card_type==='law')return{x:820+(li%2)*340,y:60+Math.floor(li/2)*180};return{x:900+(ii%2)*420,y:240+Math.floor(ii/2)*280+i*4}}
            function pos(c,i){const p=c.position||{x:0,y:0};return(typeof p.x==='number'&&typeof p.y==='number'&&(p.x!==0||p.y!==0))?p:fallback(c,i)}
            function localPatch(id,patch){if(!state.caseData)return;for(const group of[state.caseData.meta_cards,state.caseData.inference_cards,state.caseData.law_cards]){const c=group.find(x=>x.id===id);if(!c)continue;if(patch.title!==undefined)c.title=patch.title;if(patch.summary!==undefined)c.summary=patch.summary;if(patch.display_level!==undefined)c.display_level=patch.display_level;if(patch.position!==undefined)c.position=patch.position;if(patch.ui_state!==undefined)c.ui_state=patch.ui_state;if(patch.decision!==undefined&&c.card_type==='inference')c.decision=patch.decision;if(patch.detail!==undefined&&c.detail)c.detail={...c.detail,...patch.detail};c.updated_at=new Date().toISOString();state.caseData.updated_at=c.updated_at;return}}
            async function patchCard(id,patch,rerender=true){if(!state.caseData?.case_id)return;localPatch(id,patch);if(rerender)render();await json(await fetch(`${API}/api/cases/${state.caseData.case_id}/cards/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)}))}
            async function loadCase(){const data=await json(await fetch(`${API}/api/case`));state.caseData=data.case;if(!state.caseData){state.selected=[];state.focused=null}render()}
            async function runRelation(){if(!state.caseData?.case_id){setStatus('没有可生成关系的案件');return}await json(await fetch(`${API}/api/relation/run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({case_id:state.caseData.case_id})}));await loadCase();setStatus('关系已更新')}
            async function upload(files){if(!files.length)return;setStatus('正在上传并抽取材料...');const fd=new FormData();files.forEach(f=>fd.append('files',f));let r;if(state.caseData?.case_id){r=await fetch(`${API}/api/cases/${state.caseData.case_id}/files`,{method:'POST',body:fd})}else{fd.append('case_title','MVP案件');r=await fetch(`${API}/api/cases`,{method:'POST',body:fd})}const data=await json(r);state.caseData=data.case;setStatus('材料已上传，正在生成关系...');await runRelation()}
            async function generate(prompt,forcedMode=null,forcedSelection=null){if(!state.caseData?.case_id){setStatus('请先上传或加载案件');return}const mode=forcedMode||modeOf(prompt),selected=forcedSelection||genScope();setStatus(`正在生成：${mode}`);const res=await json(await fetch(`${API}/api/inference/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({case_id:state.caseData.case_id,selected_card_ids:selected,mode,user_prompt:prompt})}));const cards=res.new_inference_cards||[];if(mode==='conflict_check'){for(const c of cards)await patchCard(c.id,{decision:'pending',display_level:3},false)}await loadCase();const focus=cards.find(c=>c.inference_type==='conflict')||cards[0]||null;if(focus){state.selected=[focus.id];state.focused=focus.id;render();focusNode(focus.id)}setStatus(res.message||`已生成 ${cards.length} 张推理卡`)}
            async function retrieveLaw(conflictCardId){if(!state.caseData?.case_id){setStatus('?????????');return}setStatus('????????...');const res=await json(await fetch(`${API}/api/law/retrieve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({case_id:state.caseData.case_id,conflict_card_id:conflictCardId,selected_card_ids:[conflictCardId],intent:'support_conflict_resolution',max_results:3})}));await loadCase();state.selected=[conflictCardId,...(res.new_law_cards||[]).map(c=>c.id)];state.focused=conflictCardId;render();focusNode(conflictCardId);setStatus(res.message||`??? ${res.new_law_cards?.length||0} ???`)}
            function filePanel(){fileList.innerHTML='';const files=state.caseData?.files||[];if(!files.length){fileList.innerHTML='<div class="muted">暂无材料。点击上方“上传材料”开始。</div>';return}files.forEach(f=>{const el=document.createElement('div');el.className='item';el.innerHTML=`<div class="name">${esc(f.filename)}</div><div class="meta">${esc(f.file_type)} / ${esc(f.parse_status)}</div>`;fileList.appendChild(el)})}
            function selectionPanel(){selectionList.innerHTML='';const map=cardMap();if(!state.selected.length){selectionList.innerHTML='<div class="muted">还没有选中卡片。普通点击单选，Ctrl/Cmd + 点击多选。</div>';return}state.selected.forEach(id=>{const c=map.get(id);if(!c)return;const el=document.createElement('div');el.className='item';el.innerHTML=`<div class="name">${esc(c.title)}</div><div class="meta">${esc(typeMeta(c))}</div>`;selectionList.appendChild(el)})}
            function listBlock(title,items){if(!items.length)return `<div class="block detail"><h4>${title}</h4><div class="muted">暂无</div></div>`;return `<div class="block detail"><h4>${title}</h4><ul>${items.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></div>`}
            function titles(ids,map){return(ids||[]).map(id=>map.get(id)?.title||id).filter(Boolean)}
            function conflictBody(c,map,lvl){const support=titles(c.detail?.supporting_card_ids,map),oppose=titles(c.detail?.opposing_card_ids,map),missing=titles(c.detail?.missing_card_ids,map),legal=titles(c.detail?.legal_basis_ids,map),steps=c.detail?.reasoning_steps||[];const summary=c.summary||c.detail?.claim||'未提供冲突摘要';const actions=lvl===3?`<div class="actions detail"><button class="action" data-act="decision" data-decision="pending" data-id="${
  c.id
}
">暂存</button><button class="action" data-act="decision" data-decision="rejected" data-id="${
  c.id
}
">驳回</button><button class="action" data-act="decision" data-decision="accepted" data-id="${
  c.id
}
">确认冲突</button></div>`:`<div class="actions"><button class="action" data-act="expand" data-id="${
  c.id
}
">查看详情</button>${c.decision==='accepted'?`<button class="action" data-act="reasoning" data-id="${
  c.id
}
">生成推论</button><button class="action" data-act="missing" data-id="${
  c.id
}
">找待验证点</button>`:''}</div>`;return `<div class="summary">${esc(summary)}</div><div class="chips"><span class="chip">冲突卡</span><span class="chip ${
  esc(c.decision||'pending')
}
">${esc(decisionLabel(c.decision))}</span><span class="chip">${esc(levelLabel(lvl))}</span></div>${listBlock('支持证据',support)}${listBlock('反向证据',oppose)}${listBlock('待补证据',missing)}${listBlock('相关法条',legal)}${listBlock('推理链',steps)}${actions}`}
            function normalBody(c,lvl){if(lvl===1)return'';const summary=c.summary||c.detail?.claim||c.detail?.text||c.detail?.description||'暂无摘要';return `<div class="summary">${esc(summary)}</div>`}
            function renderNode(c,i,map){const kind=kindOf(c),lvl=c.display_level||(c.card_type==='inference'&&c.inference_type==='conflict'?2:2),p=pos(c,i),selected=state.selected.includes(c.id),focused=state.focused===c.id,rejected=c.card_type==='inference'&&c.decision==='rejected';const node=document.createElement('div');node.className=`node kind-${kind} level-${lvl}${selected?' selected':''}${focused?' focused':''}${rejected?' rejected':''}`;node.id=c.id;node.style.left=`${p.x}px`;node.style.top=`${p.y}px`;node.style.zIndex=rejected?'2':focused?'56':selected?'48':(lvl===3?'36':'12');node.innerHTML=`<div class="card"><div class="shell"><div class="head"><div class="icon">${esc(icon(kind))}</div><div class="copy"><div class="card-title">${esc(c.title)}</div><div class="card-meta">${esc(typeMeta(c))}</div></div></div>${c.card_type==='inference'&&c.inference_type==='conflict'?conflictBody(c,map,lvl):normalBody(c,lvl)}</div></div>`;bindNode(node,c);nodes.appendChild(node)}
            const edgeLabel=t=>({relates_to:'\u76f8\u5173',supports:'\u652f\u6301',opposes:'\u53cd\u9a73',derives:'\u63a8\u5bfc',mentions:'\u63d0\u53ca',conflicts_with:'\u51b2\u7a81',missing_for:'\u7f3a\u5931\u4e8e',cites:'\u5f15\u7528',belongs_to:'\u5c5e\u4e8e',grounded_in:'\u4f9d\u636e\u4e8e',applies_to:'\u9002\u7528\u4e8e',retrieved_for:'\u4e3a\u6b64\u68c0\u7d22'})[t]||t;function lineColor(edge){if(edge.edge_type==='supports'||edge.edge_type==='grounded_in'||edge.edge_type==='retrieved_for')return'rgba(62,207,142,.34)';if(edge.edge_type==='opposes'||edge.edge_type==='conflicts_with'||edge.edge_type==='missing_for')return'rgba(255,119,68,.34)';if(edge.edge_type==='cites'||edge.edge_type==='applies_to')return'rgba(244,211,94,.34)';return'rgba(255,255,255,.24)'}
            function updateLines(){links.innerHTML='';if(!state.caseData)return;for(const e of state.caseData.edges||[]){const s=document.getElementById(e.source),t=document.getElementById(e.target);if(!s||!t)continue;const sr=s.getBoundingClientRect(),tr=t.getBoundingClientRect(),cr=content.getBoundingClientRect();const sx=(sr.left-cr.left)/state.transform.scale+s.offsetWidth/2,sy=(sr.top-cr.top)/state.transform.scale+s.offsetHeight/2,tx=(tr.left-cr.left)/state.transform.scale+t.offsetWidth/2,ty=(tr.top-cr.top)/state.transform.scale+t.offsetHeight/2,dx=tx-sx,dy=ty-sy,dr=Math.max(120,Math.sqrt(dx*dx+dy*dy)*1.25);const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('class','link');path.setAttribute('d',`M ${sx+OFF},${sy+OFF} A ${dr},${dr} 0 0,1 ${tx+OFF},${ty+OFF}`);path.setAttribute('marker-end','url(#arrow)');path.style.stroke=lineColor(e);path.style.strokeWidth=String(Math.max(1.4,e.weight||1.8));links.appendChild(path)}}
            function transform(){content.style.transform=`translate(${state.transform.x}px,${state.transform.y}px) scale(${state.transform.scale})`;updateLines()}
            function fitView(){const cards=allCards().filter(c=>c.status!=='archived'&&c.status!=='hidden');if(!cards.length)return;const ps=cards.map((c,i)=>pos(c,i)),minX=Math.min(...ps.map(p=>p.x)),minY=Math.min(...ps.map(p=>p.y)),maxX=Math.max(...ps.map(p=>p.x+360)),maxY=Math.max(...ps.map(p=>p.y+260)),bw=maxX-minX,bh=maxY-minY;const sx=(wrap.clientWidth-120)/Math.max(bw,1),sy=(wrap.clientHeight-120)/Math.max(bh,1);state.transform.scale=Math.max(.45,Math.min(1,Math.min(sx,sy)));state.transform.x=60-minX*state.transform.scale;state.transform.y=60-minY*state.transform.scale;transform()}
            function focusNode(id){const node=document.getElementById(id);if(!node)return;const x=parseFloat(node.style.left||'0'),y=parseFloat(node.style.top||'0');state.transform.x=wrap.clientWidth*.5-(x+node.offsetWidth/2)*state.transform.scale;state.transform.y=wrap.clientHeight*.38-(y+node.offsetHeight/2)*state.transform.scale;transform()}
            function render(){caseTitle.textContent=state.caseData?`当前案件：${state.caseData.case_title||state.caseData.case_id}`:'当前案件：未加载';filePanel();selectionPanel();nodes.innerHTML='';links.innerHTML='';if(!state.caseData){empty.style.display='block';return}empty.style.display='none';const cards=allCards().filter(c=>c.status!=='archived'&&c.status!=='hidden'),map=cardMap();cards.forEach((c,i)=>renderNode(c,i,map));updateLines()}
            function select(id,add){if(!add)state.selected=[id];else if(state.selected.includes(id))state.selected=state.selected.filter(v=>v!==id);else state.selected=[...state.selected,id];state.focused=state.selected.length?id:null;render()}
            function queueSave(id,position){const old=state.pending.get(id);if(old)clearTimeout(old);const timer=setTimeout(async()=>{state.pending.delete(id);try{await patchCard(id,{position},false)}catch(e){setStatus(`位置保存失败：${e.message}`)}},220);state.pending.set(id,timer)}
            function bindNode(node,c){let dragging=false,sx=0,sy=0,baseX=0,baseY=0;node.addEventListener('mousedown',e=>{if(e.target.closest('[data-act]'))return;e.stopPropagation();dragging=true;sx=e.clientX;sy=e.clientY;baseX=parseFloat(node.style.left||'0');baseY=parseFloat(node.style.top||'0');node.style.zIndex='1000'});node.addEventListener('click',e=>{const a=e.target.closest('[data-act]');if(a)return;select(c.id,e.metaKey||e.ctrlKey)});node.addEventListener('dblclick',async()=>{if(c.card_type==='inference'&&c.inference_type==='conflict'&&(c.display_level||2)!==3){await patchCard(c.id,{display_level:3});setStatus('已展开冲突详情')}});node.addEventListener('click',async e=>{const a=e.target.closest('[data-act]');if(!a)return;e.stopPropagation();const act=a.dataset.act,id=a.dataset.id;if(act==='decision'){const decision=a.dataset.decision;await patchCard(id,{decision,display_level:2});setStatus(`冲突状态已更新为：${decisionLabel(decision)}`);return}if(act==='expand'){await patchCard(id,{display_level:3});setStatus('已展开冲突详情');return}if(act==='reasoning'){state.selected=[id];state.focused=id;render();await generate('基于已确认冲突生成推论','hypothesis',[id]);return}if(act==='missing'){state.selected=[id];state.focused=id;render();await generate('基于该冲突找待验证点','missing_evidence',[id])}});window.addEventListener('mousemove',e=>{if(!dragging)return;const dx=(e.clientX-sx)/state.transform.scale,dy=(e.clientY-sy)/state.transform.scale,nx=baseX+dx,ny=baseY+dy;node.style.left=`${nx}px`;node.style.top=`${ny}px`;localPatch(c.id,{position:{x:nx,y:ny}});updateLines()});window.addEventListener('mouseup',()=>{if(!dragging)return;dragging=false;node.style.zIndex=c.card_type==='inference'&&c.decision==='rejected'?'2':(state.focused===c.id?'56':'12');queueSave(c.id,{x:parseFloat(node.style.left||'0'),y:parseFloat(node.style.top||'0')})})}
            wrap.addEventListener('mousedown',e=>{if(e.target.closest('.node'))return;state.draggingCanvas=true;state.panX=e.clientX-state.transform.x;state.panY=e.clientY-state.transform.y});window.addEventListener('mousemove',e=>{if(!state.draggingCanvas)return;state.transform.x=e.clientX-state.panX;state.transform.y=e.clientY-state.panY;transform()});window.addEventListener('mouseup',()=>state.draggingCanvas=false);wrap.addEventListener('wheel',e=>{e.preventDefault();const delta=-e.deltaY*.001,scale=Math.max(.18,Math.min(2.2,state.transform.scale*Math.exp(delta))),rect=wrap.getBoundingClientRect(),mx=e.clientX-rect.left,my=e.clientY-rect.top;state.transform.x=mx-(mx-state.transform.x)*(scale/state.transform.scale);state.transform.y=my-(my-state.transform.y)*(scale/state.transform.scale);state.transform.scale=scale;transform()},{passive:false});
            document.getElementById('reloadBtn').addEventListener('click',async()=>{try{setStatus('正在刷新案件...');await loadCase();setStatus('案件已刷新')}catch(e){setStatus(`刷新失败：${e.message}`)}});document.getElementById('relationBtn').addEventListener('click',async()=>{try{await runRelation()}catch(e){setStatus(`关系生成失败：${e.message}`)}});document.getElementById('fitBtn').addEventListener('click',fitView);document.getElementById('fileInput').addEventListener('change',async e=>{const files=[...(e.target.files||[])];try{await upload(files);setStatus('上传、抽取、关系生成完成');fitView()}catch(err){setStatus(`上传失败：${err.message}`)}finally{e.target.value='';uploadZone?.classList.remove('active')}});uploadZone?.addEventListener('click',()=>document.getElementById('fileInput').click());uploadZone?.addEventListener('dragenter',e=>{e.preventDefault();uploadZone.classList.add('active')});uploadZone?.addEventListener('dragover',e=>{e.preventDefault();uploadZone.classList.add('active')});uploadZone?.addEventListener('dragleave',e=>{e.preventDefault();uploadZone.classList.remove('active')});uploadZone?.addEventListener('drop',async e=>{e.preventDefault();uploadZone.classList.remove('active');const files=[...(e.dataTransfer?.files||[])];if(!files.length)return;try{await upload(files);setStatus('上传、抽取、关系生成完成');fitView()}catch(err){setStatus(`上传失败：${err.message}`)}});document.getElementById('sendBtn').addEventListener('click',async()=>{const text=promptEl.value.trim();if(!text)return;try{await generate(text);promptEl.value=''}catch(e){setStatus(`生成失败：${e.message}`)}});promptEl.addEventListener('keydown',e=>{if(e.key!=='Enter')return;e.preventDefault();document.getElementById('sendBtn').click()});window.addEventListener('resize',updateLines);
            (async function(){try{setStatus('正在加载当前案件...');await loadCase();transform();if(state.caseData){fitView();setStatus('案件已加载')}else setStatus('当前没有案件，请先上传材料')}catch(e){setStatus(`初始化失败：${e.message}`)}})();
