"""Case service helpers for file ingestion and graph updates."""

from __future__ import annotations

import asyncio
import json
import os
from datetime import datetime
from pathlib import Path
from urllib import error as urllib_error
from urllib import request as urllib_request
from uuid import uuid4

from fastapi import UploadFile

from app.schemas import (
    CaseData,
    CaseFile,
    CardPosition,
    DisplayLevel,
    EdgeType,
    EvidenceAnchor,
    EvidenceItem,
    EvidenceType,
    FileParseStatus,
    FileType,
    GenerateInferenceRequest,
    GraphEdge,
    InferenceCard,
    InferenceDetail,
    InferenceType,
    MetaCard,
    MetaDetail,
    MetaType,
    UpdateCardRequest,
    UpdateWorkspaceRequest,
    WorkspaceState,
)


_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".bmp", ".gif", ".webp"}


def _now() -> datetime:
    return datetime.utcnow()


def _guess_file_type(filename: str, mime_type: str | None) -> FileType:
    suffix = Path(filename).suffix.lower()
    if suffix == ".pdf":
        return FileType.pdf
    if suffix == ".docx":
        return FileType.docx
    if suffix == ".txt":
        return FileType.txt
    if suffix in {".md", ".markdown"}:
        return FileType.markdown
    if suffix in _IMAGE_EXTENSIONS or (mime_type or "").startswith("image/"):
        return FileType.image
    return FileType.other


def _guess_parse_status(file_type: FileType, content: str) -> FileParseStatus:
    if file_type in {FileType.txt, FileType.markdown, FileType.image, FileType.pdf, FileType.docx}:
        return FileParseStatus.parsed
    if content.startswith("[Unsupported"):
        return FileParseStatus.failed
    return FileParseStatus.pending


def _map_evidence_type(file_type: FileType) -> EvidenceType:
    if file_type == FileType.image:
        return EvidenceType.image_region
    if file_type in {FileType.pdf, FileType.docx, FileType.txt, FileType.markdown}:
        return EvidenceType.text_span
    return EvidenceType.other


def _preview_text(text: str, limit: int = 220) -> str:
    compact = " ".join((text or "").split())
    if len(compact) <= limit:
        return compact
    return compact[: limit - 3] + "..."


def _safe_decode(raw: bytes) -> str:
    for encoding in ("utf-8", "utf-8-sig", "gbk", "latin-1"):
        try:
            return raw.decode(encoding)
        except UnicodeDecodeError:
            continue
    return raw.decode("utf-8", errors="ignore")


def _extract_content(filename: str, mime_type: str | None, raw: bytes) -> str:
    suffix = Path(filename).suffix.lower()
    if suffix in {".txt", ".md", ".markdown"}:
        return _safe_decode(raw)
    if suffix == ".pdf":
        return f"[PDF uploaded] {filename}"
    if suffix == ".docx":
        return f"[DOCX uploaded] {filename}"
    if suffix in _IMAGE_EXTENSIONS or (mime_type or "").startswith("image/"):
        return f"[Image uploaded] {filename}"
    return f"[Unsupported uploaded file type: {suffix or (mime_type or 'unknown')}]"


def _create_meta_card(title: str, summary: str, file_id: str) -> MetaCard:
    now = _now()
    return MetaCard(
        id=f"meta-{uuid4().hex[:10]}",
        title=title,
        summary=summary,
        display_level=DisplayLevel.level_1,
        position=CardPosition(x=80, y=80),
        source_file_ids=[file_id],
        created_at=now,
        updated_at=now,
        meta_type=MetaType.document,
        detail=MetaDetail(name=title, description=summary, tags=["auto-generated"]),
    )


def _mode_to_inference_type(mode: str) -> InferenceType:
    return {
        "hypothesis": InferenceType.hypothesis,
        "conclusion": InferenceType.conclusion,
        "conflict_check": InferenceType.conflict,
        "missing_evidence": InferenceType.missing_evidence,
    }.get(mode, InferenceType.hypothesis)


def _create_inference_card(claim: str, selected_ids: list[str], mode: str, title: str | None = None) -> InferenceCard:
    now = _now()
    inference_type = _mode_to_inference_type(mode)

    fallback_title = {
        InferenceType.hypothesis: "Generated Hypothesis",
        InferenceType.conclusion: "Generated Conclusion",
        InferenceType.conflict: "Potential Conflict",
        InferenceType.missing_evidence: "Missing Evidence Hint",
    }[inference_type]

    card_title = (title or "").strip() or fallback_title

    return InferenceCard(
        id=f"infer-{uuid4().hex[:10]}",
        title=card_title,
        summary=claim,
        display_level=DisplayLevel.level_2,
        position=CardPosition(x=420, y=180),
        source_file_ids=[],
        source_evidence_ids=[],
        created_at=now,
        updated_at=now,
        inference_type=inference_type,
        detail=InferenceDetail(
            claim=claim,
            reasoning_steps=["Generated by LLM."],
            supporting_card_ids=selected_ids,
            notes="Auto-generated",
        ),
    )


def create_empty_case(case_title: str, case_id: str | None = None) -> CaseData:
    now = _now()
    normalized_title = (case_title or "未命名案件").strip() or "未命名案件"
    return CaseData(
        case_id=case_id or f"case-{uuid4().hex[:8]}",
        case_title=normalized_title,
        created_at=now,
        updated_at=now,
        files=[],
        evidences=[],
        meta_cards=[],
        inference_cards=[],
        edges=[],
        workspace_state=WorkspaceState(),
    )


async def create_case_from_uploads(case_title: str, files: list[UploadFile]) -> CaseData:
    case = create_empty_case(case_title=case_title)
    if not files:
        return case

    for upload in files:
        raw = await upload.read()
        filename = upload.filename or "uploaded-file"
        mime_type = upload.content_type
        file_type = _guess_file_type(filename, mime_type)
        content = _extract_content(filename, mime_type, raw)
        parse_status = _guess_parse_status(file_type, content)
        now = _now()
        file_id = f"file-{uuid4().hex[:10]}"

        case.files.append(
            CaseFile(
                file_id=file_id,
                filename=filename,
                file_type=file_type,
                file_size=len(raw),
                storage_path=None,
                uploaded_at=now,
                parse_status=parse_status,
                preview_text=_preview_text(content),
                page_count=None,
                error_message=content if parse_status == FileParseStatus.failed else None,
            )
        )

        case.evidences.append(
            EvidenceItem(
                evidence_id=f"ev-{uuid4().hex[:10]}",
                evidence_type=_map_evidence_type(file_type),
                label=filename,
                content=content,
                summary=_preview_text(content, 120),
                anchors=[EvidenceAnchor(file_id=file_id)],
                source_file_ids=[file_id],
                created_at=now,
            )
        )

        case.meta_cards.append(
            _create_meta_card(
                title=filename,
                summary=_preview_text(content, 96) or "No extracted text.",
                file_id=file_id,
            )
        )

    case.updated_at = _now()
    return case


def upsert_case_from_payload(existing: CaseData | None, payload: CaseData) -> CaseData:
    if existing is None:
        return payload
    return payload.model_copy(update={"created_at": existing.created_at, "updated_at": _now()})


def update_card(case: CaseData, card_id: str, patch: UpdateCardRequest) -> tuple[CaseData, bool]:
    updated = False

    for card in case.meta_cards:
        if card.id != card_id:
            continue
        if patch.title is not None:
            card.title = patch.title
        if patch.summary is not None:
            card.summary = patch.summary
        if patch.display_level is not None:
            card.display_level = patch.display_level
        if patch.position is not None:
            card.position = patch.position
        if patch.ui_state is not None:
            card.ui_state = patch.ui_state
        if patch.detail is not None:
            data = card.detail.model_dump()
            data.update(patch.detail)
            card.detail = MetaDetail.model_validate(data)
        card.updated_at = _now()
        updated = True
        break

    if not updated:
        for card in case.inference_cards:
            if card.id != card_id:
                continue
            if patch.title is not None:
                card.title = patch.title
            if patch.summary is not None:
                card.summary = patch.summary
            if patch.display_level is not None:
                card.display_level = patch.display_level
            if patch.position is not None:
                card.position = patch.position
            if patch.ui_state is not None:
                card.ui_state = patch.ui_state
            if patch.detail is not None:
                data = card.detail.model_dump()
                data.update(patch.detail)
                card.detail = InferenceDetail.model_validate(data)
            card.updated_at = _now()
            updated = True
            break

    if updated:
        case.updated_at = _now()
    return case, updated


def update_workspace(case: CaseData, patch: UpdateWorkspaceRequest) -> CaseData:
    workspace = case.workspace_state
    if patch.current_view is not None:
        workspace.current_view = patch.current_view
    if patch.selected_card_ids is not None:
        workspace.selected_card_ids = patch.selected_card_ids
    if patch.focused_card_id is not None:
        workspace.focused_card_id = patch.focused_card_id
    if patch.expanded_card_ids is not None:
        workspace.expanded_card_ids = patch.expanded_card_ids
    if patch.pinned_card_ids is not None:
        workspace.pinned_card_ids = patch.pinned_card_ids
    if patch.viewport is not None:
        workspace.viewport = patch.viewport

    case.workspace_state = workspace
    case.updated_at = _now()
    return case


def generate_inference(case: CaseData, request: GenerateInferenceRequest) -> tuple[list[InferenceCard], list[GraphEdge], WorkspaceState]:
    selected = request.selected_card_ids
    claim = (request.user_prompt or "").strip() or f"{request.mode} based on {len(selected)} selected card(s)."

    new_card = _create_inference_card(claim=claim, selected_ids=selected, mode=request.mode)
    new_edges: list[GraphEdge] = []

    for source_id in selected:
        new_edges.append(
            GraphEdge(
                id=f"edge-{uuid4().hex[:10]}",
                source=source_id,
                target=new_card.id,
                edge_type=EdgeType.supports,
                label="generated",
                created_at=_now(),
            )
        )

    workspace = case.workspace_state.model_copy(deep=True)
    workspace.focused_card_id = new_card.id
    workspace.selected_card_ids = [new_card.id]

    return [new_card], new_edges, workspace


def _load_local_env() -> None:
    if os.getenv("_REASONING_ENV_LOADED") == "1":
        return

    env_path = Path(__file__).resolve().parent.parent.parent / ".env"
    if env_path.exists():
        for raw_line in env_path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip().strip("'\""))

    os.environ["_REASONING_ENV_LOADED"] = "1"


def _provider_config() -> tuple[str, str, str, str]:
    _load_local_env()
    api_key = (
        os.getenv("GITHUB_TOKEN", "").strip()
        or os.getenv("GITHUB_MODELS_TOKEN", "").strip()
        or os.getenv("OPENAI_API_KEY", "").strip()
    )
    base_url = (
        os.getenv("GITHUB_ENDPOINT", "").strip()
        or os.getenv("OPENAI_BASE_URL", "").strip()
        or "https://models.github.ai/inference"
    ).rstrip("/")
    model = (
        os.getenv("GITHUB_MODEL_ID", "").strip()
        or os.getenv("OPENAI_MODEL", "").strip()
        or "openai/gpt-4.1-mini"
    )
    api_version = os.getenv("GITHUB_API_VERSION", "2022-11-28")
    return api_key, base_url, model, api_version


def _extract_json(text: str) -> dict:
    content = (text or "").strip()
    if "```json" in content:
        content = content.split("```json", 1)[1]
    if "```" in content:
        content = content.split("```", 1)[0]
    content = content.strip()
    return json.loads(content)


def _build_inference_prompt(case: CaseData, request: GenerateInferenceRequest) -> str:
    selected = request.selected_card_ids
    selected_meta = [card for card in case.meta_cards if card.id in selected]
    selected_infer = [card for card in case.inference_cards if card.id in selected]

    return (
        f"Case title:\n{case.case_title}\n\n"
        f"Mode: {request.mode}\n"
        f"User prompt: {(request.user_prompt or '').strip() or '[empty]'}\n\n"
        f"Selected meta cards:\n{json.dumps([c.model_dump(mode='json') for c in selected_meta], ensure_ascii=False, indent=2)}\n\n"
        f"Selected inference cards:\n{json.dumps([c.model_dump(mode='json') for c in selected_infer], ensure_ascii=False, indent=2)}\n\n"
        "Return strict JSON with keys: new_inferences, new_edges.\n"
        "new_inferences: list of {title, claim, summary, inference_type, supporting_card_ids}.\n"
        "inference_type must be one of: hypothesis, conclusion, conflict, missing_evidence, reasoning_step, evidence_chain, risk, other.\n"
        "new_edges: list of {source, target_ref, edge_type, label}.\n"
        "target_ref is index notation like 'inference_0' pointing to new_inferences item.\n"
        "edge_type must be one of: relates_to,supports,opposes,derives,mentions,conflicts_with,missing_for,cites,belongs_to.\n"
        "No markdown, no extra text."
    )


def _call_llm_sync(system_prompt: str, user_prompt: str) -> dict:
    api_key, base_url, model, api_version = _provider_config()
    if not api_key:
        raise RuntimeError("No API token configured")

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.2,
    }

    data = json.dumps(payload).encode("utf-8")
    req = urllib_request.Request(
        url=f"{base_url}/chat/completions",
        data=data,
        method="POST",
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": api_version,
        },
    )

    try:
        with urllib_request.urlopen(req, timeout=30) as resp:
            body = resp.read().decode("utf-8")
    except urllib_error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="ignore") if exc.fp else str(exc)
        raise RuntimeError(f"LLM HTTP {exc.code}: {detail}") from exc
    except Exception as exc:  # pragma: no cover
        raise RuntimeError(f"LLM request failed: {exc}") from exc

    parsed = json.loads(body)
    content = parsed.get("choices", [{}])[0].get("message", {}).get("content", "")
    if isinstance(content, list):
        text_parts = []
        for item in content:
            if isinstance(item, dict) and item.get("type") == "text":
                text_parts.append(str(item.get("text", "")))
        content = "\n".join(text_parts)

    if not isinstance(content, str):
        content = str(content)

    return _extract_json(content)


async def generate_inference_with_llm(
    case: CaseData,
    request: GenerateInferenceRequest,
) -> tuple[list[InferenceCard], list[GraphEdge], WorkspaceState, str]:
    fallback_cards, fallback_edges, fallback_workspace = generate_inference(case, request)

    system_prompt = (
        "You are a legal reasoning assistant. Generate concise, evidence-grounded inference cards and graph edges. "
        "Output valid JSON only."
    )
    user_prompt = _build_inference_prompt(case, request)

    try:
        raw = await asyncio.to_thread(_call_llm_sync, system_prompt, user_prompt)
        raw_inferences = raw.get("new_inferences", [])
        raw_edges = raw.get("new_edges", [])

        if not isinstance(raw_inferences, list) or not raw_inferences:
            return fallback_cards, fallback_edges, fallback_workspace, "llm-empty-inference-fallback"

        created_cards: list[InferenceCard] = []
        for item in raw_inferences[:6]:
            if not isinstance(item, dict):
                continue
            claim = str(item.get("claim", "")).strip() or str(item.get("summary", "")).strip()
            if not claim:
                continue
            title = str(item.get("title", "")).strip() or None
            supporting = item.get("supporting_card_ids", request.selected_card_ids)
            if not isinstance(supporting, list):
                supporting = request.selected_card_ids
            mode = str(item.get("inference_type", request.mode))
            card = _create_inference_card(claim=claim, selected_ids=[str(i) for i in supporting], mode=mode, title=title)
            summary = str(item.get("summary", "")).strip()
            if summary:
                card.summary = summary
            created_cards.append(card)

        if not created_cards:
            return fallback_cards, fallback_edges, fallback_workspace, "llm-invalid-inference-fallback"

        ref_map = {f"inference_{idx}": card.id for idx, card in enumerate(created_cards)}
        created_edges: list[GraphEdge] = []

        if isinstance(raw_edges, list):
            for item in raw_edges[:40]:
                if not isinstance(item, dict):
                    continue
                source = str(item.get("source", "")).strip()
                target_ref = str(item.get("target_ref", "")).strip()
                target = ref_map.get(target_ref)
                if not source or not target:
                    continue
                edge_type_raw = str(item.get("edge_type", "supports")).strip()
                try:
                    edge_type = EdgeType(edge_type_raw)
                except Exception:
                    edge_type = EdgeType.supports
                label = str(item.get("label", "")).strip() or "generated"
                created_edges.append(
                    GraphEdge(
                        id=f"edge-{uuid4().hex[:10]}",
                        source=source,
                        target=target,
                        edge_type=edge_type,
                        label=label,
                        created_at=_now(),
                    )
                )

        if not created_edges:
            for card in created_cards:
                for source_id in request.selected_card_ids:
                    created_edges.append(
                        GraphEdge(
                            id=f"edge-{uuid4().hex[:10]}",
                            source=source_id,
                            target=card.id,
                            edge_type=EdgeType.supports,
                            label="generated",
                            created_at=_now(),
                        )
                    )

        workspace = case.workspace_state.model_copy(deep=True)
        workspace.focused_card_id = created_cards[0].id
        workspace.selected_card_ids = [created_cards[0].id]

        return created_cards, created_edges, workspace, "llm-success"
    except Exception as exc:
        return fallback_cards, fallback_edges, fallback_workspace, f"llm-fallback: {exc}"
